package com.example.bakalarkaapp.theme
import androidx.compose.ui.graphics.Color


val speech_theme_dark_primary = Color(0xFFF15226)
val speech_theme_dark_onPrimary = Color(0xFFF1F1F1)
val speech_theme_dark_primaryContainer = Color(0xFF004F52)
val speech_theme_dark_onPrimaryContainer = Color(0xFF45F9FF)
val speech_theme_dark_secondary = Color(0xFFB0CCCC)
val speech_theme_dark_onSecondary = Color(0xFF1B3435)
val speech_theme_dark_secondaryContainer = Color(0xFF324B4C)
val speech_theme_dark_onSecondaryContainer = Color(0xFFCCE8E8)
val speech_theme_dark_tertiary = Color(0xFFB5C7E9)
val speech_theme_dark_onTertiary = Color(0xFF1E314C)
val speech_theme_dark_tertiaryContainer = Color(0xFF354763)
val speech_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val speech_theme_dark_error = Color(0xFFFFB4AB)
val speech_theme_dark_errorContainer = Color(0xFF93000A)
val speech_theme_dark_onError = Color(0xFF690005)
val speech_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val speech_theme_dark_background = Color(0xFF001F5E)
val speech_theme_dark_onBackground = Color(0xFFE0E3E2)
val speech_theme_dark_surface = Color(0xFF001F5E)
val speech_theme_dark_onSurface = Color(0xFFE0E3E2)
val speech_theme_dark_surfaceVariant = Color(0xFF3F4949)
val speech_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val speech_theme_dark_outline = Color(0xFF899393)
val speech_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val speech_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val speech_theme_dark_inversePrimary = Color(0xFF00696C)
val speech_theme_dark_shadow = Color(0xFF000000)
val speech_theme_dark_surfaceTint = Color(0xFF00DCE2)
val speech_theme_dark_outlineVariant = Color(0xFF3F4949)
val speech_theme_dark_scrim = Color(0xFF000000)



val eyesight_theme_dark_primary = Color(0xFF00DCE2)
val eyesight_theme_dark_onPrimary = Color(0xFF003738)
val eyesight_theme_dark_primaryContainer = Color(0xFF004F52)
val eyesight_theme_dark_onPrimaryContainer = Color(0xFF45F9FF)
val eyesight_theme_dark_secondary = Color(0xFFB0CCCC)
val eyesight_theme_dark_onSecondary = Color(0xFF1B3435)
val eyesight_theme_dark_secondaryContainer = Color(0xFF324B4C)
val eyesight_theme_dark_onSecondaryContainer = Color(0xFFCCE8E8)
val eyesight_theme_dark_tertiary = Color(0xFFB5C7E9)
val eyesight_theme_dark_onTertiary = Color(0xFF1E314C)
val eyesight_theme_dark_tertiaryContainer = Color(0xFF354763)
val eyesight_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val eyesight_theme_dark_error = Color(0xFFFFB4AB)
val eyesight_theme_dark_errorContainer = Color(0xFF93000A)
val eyesight_theme_dark_onError = Color(0xFF690005)
val eyesight_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val eyesight_theme_dark_background = Color(0xFF001F5E)
val eyesight_theme_dark_onBackground = Color(0xFFE0E3E2)
val eyesight_theme_dark_surface = Color(0xFF001F5E)
val eyesight_theme_dark_onSurface = Color(0xFFE0E3E2)
val eyesight_theme_dark_surfaceVariant = Color(0xFF3F4949)
val eyesight_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val eyesight_theme_dark_outline = Color(0xFF899393)
val eyesight_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val eyesight_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val eyesight_theme_dark_inversePrimary = Color(0xFF00696C)
val eyesight_theme_dark_shadow = Color(0xFF000000)
val eyesight_theme_dark_surfaceTint = Color(0xFF00DCE2)
val eyesight_theme_dark_outlineVariant = Color(0xFF3F4949)
val eyesight_theme_dark_scrim = Color(0xFF000000)



val hearing_theme_dark_primary = Color(0xFFDFA50A)
val hearing_theme_dark_onPrimary = Color(0xFF003738)
val hearing_theme_dark_primaryContainer = Color(0xFF004F52)
val hearing_theme_dark_onPrimaryContainer = Color(0xFF45F9FF)
val hearing_theme_dark_secondary = Color(0xFFB0CCCC)
val hearing_theme_dark_onSecondary = Color(0xFF1B3435)
val hearing_theme_dark_secondaryContainer = Color(0xFF324B4C)
val hearing_theme_dark_onSecondaryContainer = Color(0xFFCCE8E8)
val hearing_theme_dark_tertiary = Color(0xFFB5C7E9)
val hearing_theme_dark_onTertiary = Color(0xFF1E314C)
val hearing_theme_dark_tertiaryContainer = Color(0xFF354763)
val hearing_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val hearing_theme_dark_error = Color(0xFFFFB4AB)
val hearing_theme_dark_errorContainer = Color(0xFF93000A)
val hearing_theme_dark_onError = Color(0xFF690005)
val hearing_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val hearing_theme_dark_background = Color(0xFF001F5E)
val hearing_theme_dark_onBackground = Color(0xFFE0E3E2)
val hearing_theme_dark_surface = Color(0xFF001F5E)
val hearing_theme_dark_onSurface = Color(0xFFE0E3E2)
val hearing_theme_dark_surfaceVariant = Color(0xFF3F4949)
val hearing_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val hearing_theme_dark_outline = Color(0xFF899393)
val hearing_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val hearing_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val hearing_theme_dark_inversePrimary = Color(0xFF00696C)
val hearing_theme_dark_shadow = Color(0xFF000000)
val hearing_theme_dark_surfaceTint = Color(0xFF00DCE2)
val hearing_theme_dark_outlineVariant = Color(0xFF3F4949)
val hearing_theme_dark_scrim = Color(0xFF000000)



val rythm_theme_dark_primary = Color(0xFF43B612)
val rythm_theme_dark_onPrimary = Color(0xFF003738)
val rythm_theme_dark_primaryContainer = Color(0xFF004F52)
val rythm_theme_dark_onPrimaryContainer = Color(0xFF45F9FF)
val rythm_theme_dark_secondary = Color(0xFFB0CCCC)
val rythm_theme_dark_onSecondary = Color(0xFF1B3435)
val rythm_theme_dark_secondaryContainer = Color(0xFF324B4C)
val rythm_theme_dark_onSecondaryContainer = Color(0xFFCCE8E8)
val rythm_theme_dark_tertiary = Color(0xFFB5C7E9)
val rythm_theme_dark_onTertiary = Color(0xFF1E314C)
val rythm_theme_dark_tertiaryContainer = Color(0xFF354763)
val rythm_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val rythm_theme_dark_error = Color(0xFFFFB4AB)
val rythm_theme_dark_errorContainer = Color(0xFF93000A)
val rythm_theme_dark_onError = Color(0xFF690005)
val rythm_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val rythm_theme_dark_background = Color(0xFF001F5E)
val rythm_theme_dark_onBackground = Color(0xFFE0E3E2)
val rythm_theme_dark_surface = Color(0xFF001F5E)
val rythm_theme_dark_onSurface = Color(0xFFE0E3E2)
val rythm_theme_dark_surfaceVariant = Color(0xFF3F4949)
val rythm_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val rythm_theme_dark_outline = Color(0xFF899393)
val rythm_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val rythm_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val rythm_theme_dark_inversePrimary = Color(0xFF00696C)
val rythm_theme_dark_shadow = Color(0xFF000000)
val rythm_theme_dark_surfaceTint = Color(0xFF00DCE2)
val rythm_theme_dark_outlineVariant = Color(0xFF3F4949)
val rythm_theme_dark_scrim = Color(0xFF000000)



val tales_theme_dark_primary = Color(0xFFFE67C4)
val tales_theme_dark_onPrimary = Color(0xFF003738)
val tales_theme_dark_primaryContainer = Color(0xFF004F52)
val tales_theme_dark_onPrimaryContainer = Color(0xFF45F9FF)
val tales_theme_dark_secondary = Color(0xFFB0CCCC)
val tales_theme_dark_onSecondary = Color(0xFF1B3435)
val tales_theme_dark_secondaryContainer = Color(0xFF324B4C)
val tales_theme_dark_onSecondaryContainer = Color(0xFFCCE8E8)
val tales_theme_dark_tertiary = Color(0xFFB5C7E9)
val tales_theme_dark_onTertiary = Color(0xFF1E314C)
val tales_theme_dark_tertiaryContainer = Color(0xFF354763)
val tales_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val tales_theme_dark_error = Color(0xFFFFB4AB)
val tales_theme_dark_errorContainer = Color(0xFF93000A)
val tales_theme_dark_onError = Color(0xFF690005)
val tales_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val tales_theme_dark_background = Color(0xFF001F5E)
val tales_theme_dark_onBackground = Color(0xFFE0E3E2)
val tales_theme_dark_surface = Color(0xFF001F5E)
val tales_theme_dark_onSurface = Color(0xFFE0E3E2)
val tales_theme_dark_surfaceVariant = Color(0xFF3F4949)
val tales_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val tales_theme_dark_outline = Color(0xFF899393)
val tales_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val tales_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val tales_theme_dark_inversePrimary = Color(0xFF00696C)
val tales_theme_dark_shadow = Color(0xFF000000)
val tales_theme_dark_surfaceTint = Color(0xFF00DCE2)
val tales_theme_dark_outlineVariant = Color(0xFF3F4949)
val tales_theme_dark_scrim = Color(0xFF000000)
